import { MdMonitor, MdSchema, MdShowChart, MdStackedLineChart, MdAcUnit } from 'react-icons/md';

const DEFAULT_PREVIEW = '/img/hs_resource_placeholder.png';

const productGroups = [
  {
    id: 'ngen',
    title: 'Nextgen Ecosystem',
    blurb: "Application of NOAA-OWP's NextGen Framework",
    icon: MdMonitor,
    primaryKeyword: 'nextgen_noaa',
    secondaryKeyword: 'nwm_portal_product',
    docsRoute: '/docs/products/ngen',
    defaultImage: DEFAULT_PREVIEW,
    metrics: [
      { id: 'components', label: 'Components', count: 8 },
      { id: 'apps', label: 'Applications', count: 5 },
    ],
    componentPlaceholders: [
      { id: 'ngiab-comp-1', label: 'TEEHR Integration', icon: '/img/hs_app_icon_web_light.png' },
      { id: 'ngiab-comp-2', label: 'Hydrofabric Patcher', icon: '/img/hs_code_icon_png_light.png' },
      { id: 'ngiab-comp-3', label: 'Calibration Toolkit', icon: '/img/hs_app_icon_png_light.png' },
      { id: 'ngiab-comp-4', label: 'Docker Distribution', icon: '/img/apps_light_theme.png' },
      { id: 'ngiab-comp-5', label: 'Visualization Suite', icon: '/img/portal_apps_light.png' },
      { id: 'ngiab-comp-6', label: 'Community Repos', icon: '/img/docuhub_light.png' },
    ],
    products: [
      {
        id: 'ngiab-preprocessor',
        title: 'NGIAB Data Preprocess',
        type: 'Library',
        summary: 'Interactive tool to pre process input data for ngiab',
        icon: '/img/portal_apps_light.png',
        docsLink: '/docs/products/ngiab/components/ngiab-preprocessor',
      },
      {
        id: 'ngiab-teehr',
        title: 'TEEHR Integration',
        type: 'Library',
        summary: 'TEEHR-powered pipelines to benchmark NextGen simulations.',
        icon: '/img/hs_app_icon_web_light.png',
        docsLink: '/docs/products/ngiab/components/ngiab-teehr',
      },
      {
        id: 'ngiab-docker',
        title: 'NGIAB Docker Suite',
        type: 'Framework',
        summary: 'Pre-built Docker images for cross-platform experimentation.',
        icon: '/img/apps_light_theme.png',
        docsLink: '/docs/products/ngiab/distributions/ngiab-docker',
      },
      {
        id: 'ngiab-calibration',
        title: 'Calibration Toolkit',
        type: 'Library',
        summary: 'Automated calibration workflows with Cloud-optimized storage.',
        icon: '/img/hs_app_icon_png_light.png',
        docsLink: '/docs/products/ngiab/components/ngiab-calibration',
      },
      {
        id: 'ngiab-visualization',
        title: 'Visualization Suite',
        type: 'Application',
        summary: 'Interactive dashboards for NextGen model output analysis.',
        icon: '/img/portal_apps_light.png',
        docsLink: '/docs/products/ngiab/components/ngiab-visualization',
      },
       {
        id: 'ngiab-exploration',
        title: 'Jupyter Exploration Notebooks',
        type: 'Jupyter Notebook',
        summary: 'Interactive Jupyter notebooks for NextGen model output analysis.',
        icon: '/img/portal_apps_light.png',
        docsLink: '/docs/products/ngiab/components/ngiab-visualization',
      },
      {
        id: 'ngiab-datastream',
        title: 'Datastream Dataset',
        type: 'Dataset',
        summary: 'NextGen model output datasets for analysis and visualization.',
        icon: '/img/portal_apps_light.png',
        docsLink: '/docs/products/ngiab/components/ngiab-visualization',
      },
       {
        id: 'ngiab-datasets',
        title: 'Comprehensive Datasets',
        type: 'Dataset',
        summary: 'Extensive datasets supporting NextGen experiments and analyses.',
        icon: '/img/portal_apps_light.png',
        docsLink: '/docs/products/ngiab/components/ngiab-visualization',
      },
      
    ],
  },
  {
    id: 'hydrofabric',
    title: 'Community Hydrofabric',
    blurb: 'Hydrofabric assets and editors curated for the NOAA National Water Model.',
    icon: MdSchema,
    primaryKeyword: 'hydrofabric_portal_app',
    secondaryKeyword: 'hydrofabric_portal_module',
    docsRoute: '/docs/products/ngiab/components/community-hydrofabric',
    defaultImage: DEFAULT_PREVIEW,
    metrics: [
      { id: 'components', label: 'Components', count: 5 },
      { id: 'apps', label: 'Applications', count: 2 },
    ],
    componentPlaceholders: [
      { id: 'hydrofabric-comp-1', label: 'Hydrofabric Overview', icon: '/img/datasets_light.png' },
      { id: 'hydrofabric-comp-2', label: 'Data Download', icon: '/img/home_datasets_light.png' },
      { id: 'hydrofabric-comp-3', label: 'Editing Tools', icon: '/img/hs_code_icon_png_light.png' },
      { id: 'hydrofabric-comp-4', label: 'Repository Dashboard', icon: '/img/apps_light_theme.png' },
      { id: 'hydrofabric-comp-5', label: 'Community Stories', icon: '/img/docuhub_light.png' },
      { id: 'hydrofabric-comp-6', label: 'Support Resources', icon: '/img/docuhub_pr_light.png' },
    ],
    products: [
      {
        id: 'hydrofabric-editor',
        title: 'Hydrofabric Editor',
        type: 'Application',
        summary: 'Browser-based tools to edit and QA national hydrofabric assets.',
        icon: '/img/datasets_light.png',
        docsLink: '/docs/products/ngiab/components/community-hydrofabric',
      },
      {
        id: 'hydrofabric-api',
        title: 'Hydrofabric API',
        type: 'Service',
        summary: 'REST endpoints for mesh download, lineage, and metadata.',
        icon: '/img/hs_app_urls_light.png',
        docsLink: '/docs/products/ngiab/components/community-hydrofabric',
      },
      {
        id: 'hydrofabric-dashboard',
        title: 'Repository Dashboard',
        type: 'Analytics',
        summary: 'Live health metrics for hydrofabric forks and pending PRs.',
        icon: '/img/docuhub_pr_light.png',
        docsLink: '/docs/products/ngiab/components/community-hydrofabric',
      },
    ],
  },
  {
    id: 'community-fim',
    title: 'Community Flood Inundation Mapping',
    blurb: 'Visualization and evaluation tooling for flood inundation modeling studies.',
    icon: MdShowChart,
    primaryKeyword: 'community_fim_portal_app',
    secondaryKeyword: 'community_fim_portal_module',
    docsRoute: '/docs/products/community-fim',
    defaultImage: DEFAULT_PREVIEW,
    metrics: [
      { id: 'apps', label: 'Applications', count: 4 },
      { id: 'reports', label: 'Reports', count: 6 },
    ],
    componentPlaceholders: [
      { id: 'community-fim-comp-1', label: 'FIMSERV', icon: '/img/hs_app_light.png' },
      { id: 'community-fim-comp-2', label: 'FIM Evaluation', icon: '/img/hs_app_dark.png' },
      { id: 'community-fim-comp-3', label: 'FIM Database', icon: '/img/hs_app_urls_light.png' },
      { id: 'community-fim-comp-4', label: 'Training Resources', icon: '/img/hydrolearn_101_light.png' },
      { id: 'community-fim-comp-5', label: 'Case Studies', icon: '/img/docuhub_dark.png' },
      { id: 'community-fim-comp-6', label: 'Community Events', icon: '/img/join_community_light.png' },
    ],
    products: [
      {
        id: 'fimserv',
        title: 'FIMSERV',
        type: 'Library',
        summary: 'Rapidly request FIM runs through a managed service.',
        icon: '/img/hs_app_light.png',
        docsLink: '/docs/products/community-fim',
      },
      {
        id: 'fim-eval',
        title: 'FIM Evaluation',
        type: 'Library',
        summary: 'Compare flood extents and scores across scenarios.',
        icon: '/img/hs_app_dark.png',
        docsLink: '/docs/products/community-fim',
      },
      {
        id: 'fim-database',
        title: 'FIM Database',
        type: 'Application',
        summary: 'Curated FIM rasters and event metadata for repeat analysis.',
        icon: '/img/hs_app_urls_light.png',
        docsLink: '/docs/products/community-fim',
      },
    ],
  },
  {
    id: 'research-datastream',
    title: 'Research Datastream',
    blurb: 'APIs, CLIs, and downstream utilities that serve NextGen modeling data.',
    icon: MdStackedLineChart,
    primaryKeyword: 'research_datastream_portal_app',
    secondaryKeyword: 'research_datastream_portal_module',
    docsRoute: '/docs/products/research-datastream',
    defaultImage: DEFAULT_PREVIEW,
    metrics: [
      { id: 'components', label: 'Components', count: 6 },
      { id: 'pipelines', label: 'Pipelines', count: 4 },
    ],
    componentPlaceholders: [
      { id: 'research-ds-comp-1', label: 'CLI Overview', icon: '/img/modules_light.png' },
      { id: 'research-ds-comp-2', label: 'Model Catalog', icon: '/img/hs_app_icon_png_light.png' },
      { id: 'research-ds-comp-3', label: 'Data Status', icon: '/img/home_datasets_dark.png' },
      { id: 'research-ds-comp-4', label: 'API Endpoints', icon: '/img/hs_code_icon_png_light.png' },
      { id: 'research-ds-comp-5', label: 'Sample Workflows', icon: '/img/docuhub_md_light3.png' },
      { id: 'research-ds-comp-6', label: 'Integration Guides', icon: '/img/docuhub_fork_light.png' },
    ],
    products: [
      {
        id: 'datastream-cli',
        title: 'Datastream CLI',
        type: 'Framework',
        summary: 'Command-line interface for streaming NextGen inputs.',
        icon: '/img/modules_light.png',
        docsLink: '/docs/products/research-datastream',
      },
      {
        id: 'nwm-repo-dashboard',
        title: 'nwmurl',
        type: 'Library',
        summary: 'nwmurl provides utility functions specifically designed to subset and generate National Water Model (NWM) data URLs',
        icon: '/img/docuhub_pr_light.png',
        docsLink: '/docs/products/research-datastream',
      },
      {
        id: 'datastream-forcing-processor',
        title: 'Forcing Processor',
        type: 'Library',
        summary: 'Forcingprocessor converts National Water Model (NWM) forcing data into Next Generation National Water Model (NextGen) forcing data',
        icon: '/img/docuhub_md_light3.png',
        docsLink: '/docs/products/research-datastream',
      },
    ],
  },
  {
    id: 'snow-tools',
    title: 'Snow Sensing & Modeling',
    blurb: 'Snow water equivalent tools, calibration notebooks, and decision dashboards.',
    icon: MdAcUnit,
    primaryKeyword: 'snow_tools_portal_app',
    secondaryKeyword: 'snow_tools_portal_module',
    docsRoute: '/docs/products/snow-tools',
    defaultImage: DEFAULT_PREVIEW,
    metrics: [
      { id: 'apps', label: 'Applications', count: 3 },
      { id: 'tools', label: 'Tools', count: 4 },
    ],
    componentPlaceholders: [
      { id: 'snow-tools-comp-1', label: 'Snow Sensing', icon: '/img/hydrolearn_logo.png' },
      { id: 'snow-tools-comp-2', label: 'Sensor Optimization', icon: '/img/hs_app_icon_web_light.png' },
      { id: 'snow-tools-comp-3', label: 'SWEML v2.0', icon: '/img/hydrolearn_101_light.png' },
      { id: 'snow-tools-comp-4', label: 'Training Modules', icon: '/img/modules_light.png' },
      { id: 'snow-tools-comp-5', label: 'Data Products', icon: '/img/home_datasets_light.png' },
      { id: 'snow-tools-comp-6', label: 'Community Highlights', icon: '/img/join_community_light.png' },
    ],
    products: [
      {
        id: 'sweml',
        title: 'SWEML v2.0',
        type: 'Application',
        summary: 'Machine-learning snow forecasts with explainable cards.',
        icon: '/img/hydrolearn_101_light.png',
        docsLink: '/docs/products/snow-tools',
      },
      {
        id: 'snow-inspector',
        title: 'Snow Inspector',
        type: 'Visualization',
        summary: 'MODIS-based explorer for snow depth and SWE anomalies.',
        icon: '/img/hs_app_icon_web_light.png',
        docsLink: '/docs/products/snow-tools',
      },
      {
        id: 'sensor-optimizer',
        title: 'Sensor Optimizer',
        type: 'Tool',
        summary: 'Greedy placement assistant for alpine sensor networks.',
        icon: '/img/home_learning_ modules_light.png',
        docsLink: '/docs/products/snow-tools',
      },
    ],
  },
];

export default productGroups;
